name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start Expo server
        run: |
          echo "Starting Expo server on port 8081..."
          npx expo start --web --port 8081 &
          sleep 20
          echo "Expo server started."
        env:
          EXPO_WEB_PORT: 8081
          CI: 1

      - name: Check if Expo server is running
        run: curl -v http://localhost:8081

      - name: Wait for Expo server to be ready
        run: npx wait-on http://localhost:8081

      - name: Run tests
        run: npx jest
